#include "BIS_AddonInfo.hpp"
class CfgPatches
{
	class LG_animations
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.0099999998;
		requiredAddons[]=
		{
			"A3_Anims_F",
			"A3_Anims_F_Config_Sdr"
		};
		version=1;
	};
};

class CfgMovesBasic
{
	access=1;
	skeletonName="";
	collisionVertexPattern[]=
	{
		"1a",
		"2a",
		"3a",
		"4a",
		"5a",
		"6a",
		"7a",
		"8a",
		"9a",
		"10a",
		"11a",
		"12a",
		"13a",
		"14a",
		"15a",
		"16a",
		"17a",
		"18a",
		"19a",
		"20a",
		"21a",
		"22a",
		"23a",
		"24a",
		"25a",
		"26a",
		"27a",
		"28a",
		"29a",
		"30a",
		"31a",
		"32a",
		"33a",
		"34a",
		"1c",
		"2c",
		"3c",
		"4c",
		"5c",
		"6c",
		"7c",
		"8c"
	};
	collisionGeomCompPattern[]={1,3};
	class Default;
	class StandBase;
	class AmovPercMstpSnonWnonDnon: StandBase
	{
	};
	class AmovPpneMstpSnonWnonDnon: AmovPercMstpSnonWnonDnon
	{
	};
	class LG_anim_AmovPpneMstpSnonWnonDnon: AmovPpneMstpSnonWnonDnon
	{
	};
	class DefaultDie;
	class ManActions
	{
		LG_anim_ArrestedIn="LG_anim_ArrestedIn";
		LG_anim_ArrestedLoop="LG_anim_ArrestedLoop";
		LG_anim_ArrestedOut="LG_anim_ArrestedOut";
		LG_anim_ArrestedSit="LG_anim_ArrestedSit";
		LG_anim_ArrestedProne="LG_anim_ArrestedProne";
		LG_anim_codecrackerATM="LG_anim_codecrackerATM";
		LG_anim_drill_short="LG_anim_drill_short";
		LG_anim_managerdoorlockpick="LG_anim_managerdoorlockpick";
		LG_anim_placeC4[]=
		{
			"LG_anim_placeC4",
			"Gesture"
		};
		LG_anim_beartrap1="LG_anim_beartrap1";
		LG_anim_beartrap2="LG_anim_beartrap2";
		LG_anim_halt="LG_anim_halt";
		LG_DuoIvan="LG_DuoIvan";
		LG_DuoStephan="LG_DuoStephan";
		LG_Stephan="LG_Stephan";
		LG_FastRoping_animation="LG_FastRoping_animation";
		LG_anim_GatheringIn1="LG_anim_GatheringIn1";
		LG_anim_GatheringIn2="LG_anim_GatheringIn2";
		LG_anim_GatheringIn3="LG_anim_GatheringIn3";
		LG_anim_GatheringIn4="LG_anim_GatheringIn4";
		LG_anim_GatheringIn5="LG_anim_GatheringIn5";
		LG_anim_GatheringIn6="LG_anim_GatheringIn6";
		LG_anim_GatheringOut="LG_anim_GatheringOut";
		LG_anim_Gathering1="LG_anim_Gathering1";
		LG_anim_Gathering2="LG_anim_Gathering2";
		LG_anim_Gathering3="LG_anim_Gathering3";
		LG_anim_Gathering4="LG_anim_Gathering4";
		LG_anim_Gathering5="LG_anim_Gathering5";
		LG_anim_Gathering6="LG_anim_Gathering6";
		LG_anim_halt2="LG_anim_halt2";
		LG_anim_HandsUp="LG_anim_HandsUp";
		LG_anim_HandsLoop="LG_anim_HandsLoop";
		LG_anim_HandsDown="LG_anim_HandsDown";
		LG_anim_pron_grinder="LG_anim_pron_grinder";
		LG_anim_lockpick="LG_anim_lockpick";
		LG_bouncer="LG_bouncer";
		LG_bow_pray="LG_bow_pray";
		LG_clapping="LG_clapping";
		LG_hand_stand="LG_hand_stand";
		LG_muscle="LG_muscle";
		LG_pushups="LG_pushups";
		LG_violin="LG_violin";
		LG_wank="LG_wank";
		LG_yoyo="LG_yoyo";
		
		LG_suck_it[]=
		{
			"LG_suck_it",
			"Gesture"
		};
		LG_thumbs_down[]=
		{
			"LG_thumbs_down",
			"Gesture"
		};
		LG_thumbs_up[]=
		{
			"LG_thumbs_up",
			"Gesture"
		};
		LG_wanker[]=
		{
			"LG_wanker",
			"Gesture"
		};
		LG_no_way[]=
		{
			"LG_no_way",
			"Gesture"
		};
		LG_yes[]=
		{
			"LG_yes",
			"Gesture"
		};
		LG_that_way[]=
		{
			"LG_that_way",
			"Gesture"
		};
		LG_hitchhiking[]=
		{
			"LG_hitchhiking",
			"Gesture"
		};
		LG_anim_Wank="LG_anim_Wank";
		LG_anim_pliers="LG_anim_pliers";
		LG_anim_PunchRandom="LG_anim_PunchRandom";
		LG_anim_Punch1="LG_anim_Punch1";
		LG_anim_Punch2="LG_anim_Punch2";
		LG_anim_Punch3="LG_anim_Punch3";
		LG_anim_Punch4="LG_anim_Punch4";
		LG_anim_Receive1a="LG_anim_Receive1a";
		LG_anim_Receive1b="LG_anim_Receive1b";
		LG_anim_Receive2a="LG_anim_Receive2a";
		LG_anim_Receive2b="LG_anim_Receive2b";
		LG_anim_Receive3a="LG_anim_Receive3a";
		LG_anim_Receive3b="LG_anim_Receive3b";
		LG_anim_Receive3c="LG_anim_Receive3c";
		LG_anim_Receive4="LG_anim_Receive4";
		LG_anim_Knockout1In="LG_anim_Knockout1In";
		LG_anim_Knockout1End="LG_anim_Knockout1End";
		LG_anim_Knockout2In="LG_anim_Knockout2In";
		LG_anim_Knockout2End="LG_anim_Knockout2End";
		LG_anim_WeaponHit="LG_anim_WeaponHit";
		LG_push_animation="LG_push_animation";
		CL3_anim_RepairCrouch="CL3_anim_RepairCrouch";
		LG_anim_surrenderstart="LG_anim_surrenderstart";
		LG_anim_surrenderloop="LG_anim_surrenderloop";
		LG_anim_surrenderfinish="LG_anim_surrenderfinish";
		LG_anim_Shovel="LG_anim_Shovel";
		LG_anim_Hammer[]=
		{
			"LG_anim_Hammer",
			"Gesture"
		};
		CRPTHSForward[]=
		{
			"CRPTHSForward",
			"Gesture"
		};
		CRPTHSStop[]=
		{
			"CRPTHSStop",
			"Gesture"
		};
		CRPTHSCover[]=
		{
			"CRPTHSCover",
			"Gesture"
		};
		CRPTHSRegroup[]=
		{
			"CRPTHSRegroup",
			"Gesture"
		};
		CRPTHSEngage[]=
		{
			"CRPTHSEngage",
			"Gesture"
		};
		CRPTHSPoint[]=
		{
			"CRPTHSPoint",
			"Gesture"
		};
		CRPTHSHold[]=
		{
			"CRPTHSHold",
			"Gesture"
		};
		CRPTHSWarning[]=
		{
			"CRPTHSWarning",
			"Gesture"
		};
		CRPTHSForwardStandLowered[]=
		{
			"CRPTHSForwardStandLowered",
			"Gesture"
		};
		CRPTHSStopStandLowered[]=
		{
			"CRPTHSStopStandLowered",
			"Gesture"
		};
		CRPTHSCoverStandLowered[]=
		{
			"CRPTHSCoverStandLowered",
			"Gesture"
		};
		CRPTHSRegroupStandLowered[]=
		{
			"CRPTHSRegroupStandLowered",
			"Gesture"
		};
		CRPTHSEngageStandLowered[]=
		{
			"CRPTHSEngageStandLowered",
			"Gesture"
		};
		CRPTHSPointStandLowered[]=
		{
			"CRPTHSPointStandLowered",
			"Gesture"
		};
		CRPTHSHoldStandLowered[]=
		{
			"CRPTHSHoldStandLowered",
			"Gesture"
		};
		CRPTHSWarningStandLowered[]=
		{
			"CRPTHSWarningStandLowered",
			"Gesture"
		};
	};
	class Actions
	{
		class NoActions: ManActions
		{
		};
	};
};
class CfgMovesMaleSdr: CfgMovesBasic
{
	skeletonName="OFP2_ManSkeleton";
	gestures="CfgGesturesMale";
	class States
	{
		class AinvPknlMstpSnonWnonDnon_medic;
		class AmovPpneMstpSnonWnonDnon;
		class AmovPercMstpSnonWnonDnon_falling;
		class Crew;
		class CutSceneAnimationBase;
		class AidlPercMstpSrasWrflDnon_AI;
		class AmovPercMstpSlowWrflDnon;
		class AmovPercMstpSnonWnonDnon;
		class ActsPsitMstpSnonWunaDnon_sceneNikitinDisloyalty_Cooper: CutSceneAnimationBase
		{
			speed=0.00771;
			file="\LG_animations\ip_a2c\anims\ActsPsitMstpSnonWunaDnon_sceneNikitinDisloyalty_Cooper";
			looped=0;
			actions="RifleLowStandActions";
			disableWeapons=1;
			enableOptics=0;
			enableBinocular=0;
			canPullTrigger=0;
			headBobMode=0;
			headBobStrength=0;
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.0099999998
			};
			InterpolateTo[]={};
		};
		/*class AmovPercMstpSnonWnonDnon_exerciseKata: CutSceneAnimationBase
		{
			file="\LG_animations\ip_a2c\anims\AmovPercMstpSnonWnonDnon_exerciseKata.rtm";
			speed=0.029999999;
			canPullTrigger=0;
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				2,
				"AmovPercMstpSnonWnonDnon_exerciseKata",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.0099999998
			};
		};*/
		class ActsPknlMstpSnonWnonDnon_TreatingInjured_NikitinDead: CutSceneAnimationBase
		{
			file="\LG_animations\ip_a2c\anims\ActsPknlMstpSnonWnonDnon_TreatingInjured.rtm";
			speed=0.025;
			enableBinocular=0;
			canPullTrigger=0;
			ConnectTo[]=
			{
				"AdthPercMstpSrasWrflDnon_NikitinDead2",
				0.0099999998
			};
			InterpolateTo[]=
			{
				"AdthPercMstpSrasWrflDnon_NikitinDead2",
				0.0099999998
			};
		};
		class AdthPercMstpSrasWrflDnon_NikitinDead2: ActsPknlMstpSnonWnonDnon_TreatingInjured_NikitinDead
		{
			file="\LG_animations\ip_a2c\anims\AdthPercMstpSrasWrflDnon_NikitinDead.rtm";
			speed=1.05;
			looped=0;
			terminal=0;
			ConnectTo[]={};
			InterpolateTo[]={};
		};
		class LG_anim_ArrestedIn: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\arrest\anims\ArrestedIn.rtm";
			speed=-3;
			looped=0;
			soundEnabled=0;
			duty=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]=
			{
				"LG_anim_ArrestedLoop",
				0.1
			};
			InterpolateTo[]=
			{
				"LG_anim_ArrestedLoop",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_ArrestedLoop: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\arrest\anims\ArrestedLoop.rtm";
			speed=1e+010;
			looped=0;
			duty=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"LG_anim_ArrestedOut",
				0.1,
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_ArrestedOut: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\arrest\anims\ArrestedOut.rtm";
			speed=-3;
			looped=0;
			duty=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_ArrestedProne: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\arrest\anims\ArrestedProne.rtm";
			speed=1e+010;
			looped=0;
			duty=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_ArrestedSit: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\arrest\anims\ArrestedSit.rtm";
			speed=1e+010;
			looped=0;
			duty=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_codecrackerATM: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-15;
			file="\LG_animations\bank\anim\codecrackerATM.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.80000001,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_drill_short: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-2.3;
			file="\LG_animations\bank\anim\drill_short.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.80000001,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_managerdoorlockpick: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-14;
			file="\LG_animations\bank\anim\managerdoorlockpick.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.80000001,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_beartrap1: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-4;
			file="\LG_animations\beartrap\anims\beartrap1.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			connectTo[]=
			{
				"LG_anim_beartrap2",
				0.1
			};
			InterpolateTo[]=
			{
				"LG_anim_beartrap2",
				0.2,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_beartrap2: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-20;
			file="\LG_animations\beartrap\anims\beartrap2.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			connectTo[]=
			{
				"AmovPpneMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPpneMstpSnonWnonDnon",
				0.60000002,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_halt: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-15;
			file="\LG_animations\CopActions\anims\halt.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"LG_anim_beartrap2",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_DuoIvan: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-39.299999;
			file="\LG_animations\dance\anims\DuoIvan.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class LG_DuoStephan: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-39.299999;
			file="\LG_animations\dance\anims\DuoStephan.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class LG_Stephan: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-96.300003;
			file="\LG_animations\dance\anims\Stephan.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class LG_FastRoping_animation: Crew
		{
			file="\LG_animations\fastrope\FastRoping_animation.rtm";
			interpolateTo[]=
			{
				"Unconscious",
				1
			};
		};
		class LG_anim_GatheringIn1: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.55000001;
			file="\LG_animations\gathering\anims\LG_anim_GatheringIn.rtm";
			looped=0;
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"LG_anim_Gathering1",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class LG_anim_GatheringIn2: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.55000001;
			file="\LG_animations\gathering\anims\LG_anim_GatheringIn.rtm";
			looped=0;
			soundEnabled=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"LG_anim_Gathering2",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class LG_anim_GatheringIn3: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.55000001;
			file="\LG_animations\gathering\anims\LG_anim_GatheringIn.rtm";
			looped=0;
			soundEnabled=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"LG_anim_Gathering3",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class LG_anim_GatheringIn4: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.55000001;
			file="\LG_animations\gathering\anims\LG_anim_GatheringIn.rtm";
			looped=0;
			soundEnabled=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"LG_anim_Gathering4",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class LG_anim_GatheringIn5: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.55000001;
			file="\LG_animations\gathering\anims\LG_anim_GatheringIn.rtm";
			looped=0;
			soundEnabled=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"LG_anim_Gathering5",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class LG_anim_GatheringIn6: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.55000001;
			file="\LG_animations\gathering\anims\LG_anim_GatheringIn.rtm";
			looped=0;
			soundEnabled=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"LG_anim_Gathering6",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Gathering1: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.20999999;
			file="\LG_animations\gathering\anims\LG_anim_Gathering1.rtm";
			looped=0;
			soundEnabled=0;
			canBlendStep=0;
			ConnectTo[]=
			{
				"LG_anim_GatheringOut",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Gathering2: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.17;
			file="\LG_animations\gathering\anims\LG_anim_Gathering2.rtm";
			looped=0;
			soundEnabled=0;
			canBlendStep=0;
			ConnectTo[]=
			{
				"LG_anim_GatheringOut",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Gathering3: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.14;
			file="\LG_animations\gathering\anims\LG_anim_Gathering3.rtm";
			looped=0;
			soundEnabled=0;
			canBlendStep=0;
			ConnectTo[]=
			{
				"LG_anim_GatheringOut",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Gathering4: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.090000004;
			file="\LG_animations\gathering\anims\LG_anim_Gathering4.rtm";
			looped=0;
			soundEnabled=0;
			canBlendStep=0;
			ConnectTo[]=
			{
				"CL3_anim_GatheringOut",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Gathering5: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.17;
			canBlendStep=0;
			file="\LG_animations\gathering\anims\LG_anim_Gathering5.rtm";
			looped=0;
			soundEnabled=0;
			ConnectTo[]=
			{
				"LG_anim_GatheringOut",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Gathering6: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			speed=0.15000001;
			canBlendStep=0;
			forceAim=1;
			file="\LG_animations\gathering\anims\LG_anim_Gathering6.rtm";
			looped=0;
			soundEnabled=0;
			ConnectTo[]=
			{
				"LG_anim_GatheringOut",
				0.1
			};
			InterpolateTo[]={};
		};
		class LG_anim_GatheringOut: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			canBlendStep=0;
			minPlayTime=1;
			speed=0.55000001;
			file="\LG_animations\gathering\anims\LG_anim_GatheringOut.rtm";
			looped=0;
			soundEnabled=0;
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_halt2: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-13;
			file="\LG_animations\halt\anims\LG_anims_halt.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class LG_anim_HandsUp: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\HandsUp\anims\HandsUp.rtm";
			speed=0.64999998;
			looped=0;
			soundEnabled=0;
			duty=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]=
			{
				"LG_anim_HandsLoop",
				0.1
			};
			InterpolateTo[]=
			{
				"LG_anim_HandsLoop",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_HandsLoop: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\HandsUp\anims\HandsLoop.rtm";
			speed=1e+010;
			looped=0;
			soundEnabled=0;
			duty=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"LG_anim_HandsDown",
				0.1,
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_HandsDown: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\HandsUp\anims\HandsDown.rtm";
			speed=0.69999999;
			looped=0;
			duty=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_pron_grinder: AmovPpneMstpSnonWnonDnon
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-14.602;
			file="\LG_animations\Jail\anims\pron_grinder.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPpneMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPpneMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class LG_anim_lockpick: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-7.5999999;
			file="\LG_animations\Lockpicking\anims\lockpicking.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class LG_bouncer: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-13.7;
			file="\LG_animations\menu_gestures\anims\bouncer.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class LG_bow_pray: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-15.8;
			file="\LG_animations\menu_gestures\anims\bow_pray.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class LG_clapping: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-10.7;
			file="\LG_animations\menu_gestures\anims\clapping.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class LG_hand_stand: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-7;
			file="\LG_animations\menu_gestures\anims\hand_stand.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class LG_muscle: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-10.3;
			file="\LG_animations\menu_gestures\anims\muscle.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class LG_pushups: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-10;
			file="\LG_animations\menu_gestures\anims\pushups.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class LG_violin: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-13;
			file="\LG_animations\menu_gestures\anims\violin.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class LG_wank: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-7.3000002;
			file="\LG_animations\menu_gestures\anims\wank.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class LG_yoyo: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-20.299999;
			file="\LG_animations\menu_gestures\anims\yoyo.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class CL3_anim_Portaloo: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\naturescall\anims\Portaloo.rtm";
			speed=-30;
			looped=0;
			soundEnabled=0;
			duty=0;
			disableWeapons=0;
			minPlayTime=1;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Wank: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\naturescall\anims\wanking.rtm";
			speed=-6;
			looped=0;
			duty=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_pliers: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.188757;
			file="\LG_animations\pliers\anims\pliers.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class LG_anim_PunchRandom: AinvPknlMstpSnonWnonDnon_medic
		{
			variantsPlayer[]=
			{
				"LG_anim_Punch1",
				0.25,
				"LG_anim_Punch2",
				0.25,
				"LG_anim_Punch3",
				0.25,
				"LG_anim_Punch4",
				0.25
			};
			variantAfter[]={1,5,10};
			speed=0.55000001;
			file="\LG_animations\punch\anims\Punch1.rtm";
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateFrom[]=
			{
				"AmovPercMstpSrasWpstDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Punch1: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\punch\anims\Punch1.rtm";
			speed=0.55000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Punch2: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\punch\anims\Punch2.rtm";
			speed=0.55000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Punch3: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\punch\anims\Punch3.rtm";
			speed=0.55000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Punch4: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\punch\anims\Punch4.rtm";
			speed=0.55000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Receive1a: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\punch\anims\Receive1a.rtm";
			speed=0.30000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Receive1b: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\punch\anims\Receive1b.rtm";
			speed=0.30000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Receive2a: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\punch\anims\Receive2a.rtm";
			speed=0.30000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Receive2b: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\punch\anims\Receive2b.rtm";
			speed=0.30000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Receive3a: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\punch\anims\Receive3a.rtm";
			speed=0.44999999;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Receive3b: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\punch\anims\Receive3b.rtm";
			speed=0.30000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Receive3c: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\punch\anims\Receive3c.rtm";
			speed=0.30000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Receive4: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\punch\anims\Receive4.rtm";
			speed=0.30000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Knockout1In: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\punch\anims\KnockOut1In.rtm";
			speed=0.27000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"LG_anim_Knockout1End",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Knockout1End: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\punch\anims\KnockOut1End.rtm";
			speed=0.27000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Knockout2In: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\punch\anims\KnockOut2In.rtm";
			speed=0.30000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"LG_anim_Knockout2End",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Knockout2End: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\punch\anims\KnockOut2End.rtm";
			speed=0.25;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_WeaponHit: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\punch\anims\WeaponHit.rtm";
			speed=0.25;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_push_animation: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-0.69999999;
			file="\LG_animations\push\anims\push.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_RepairCrouch: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-27;
			file="\LG_animations\repair\anims\CL3_anim_RepairCrouch.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class cl3_smoke_cig_anim: CutSceneAnimationBase
		{
			file="\LG_animations\smoke\smoke.rtm";
			speed=0.188757;
			boundingSphere=4;
			collisionShape="A3\anims_f\Data\Geom\Sdr\geom_empty.p3d";
			ConnectTo[]={};
			InterpolateTo[]={};
		};
		class LG_anim_surrenderstart: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\surrender\anims\surrenderstart.rtm";
			speed=-3;
			looped=0;
			soundEnabled=0;
			duty=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]=
			{
				"LG_anim_surrenderloop",
				0.1
			};
			InterpolateTo[]=
			{
				"LG_anim_surrenderloop",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_surrenderLoop: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\surrender\anims\surrenderloop.rtm";
			speed=1e+010;
			looped=0;
			soundEnabled=0;
			duty=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"LG_anim_surrenderfinish",
				0.1,
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_surrenderfinish: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\LG_animations\surrender\anims\surrenderfinish.rtm";
			speed=-2;
			looped=0;
			duty=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class LG_anim_Shovel: AidlPercMstpSrasWrflDnon_AI
		{
			file="\LG_animations\tools\anims\Shovel.rtm";
			speed=-6;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
	};
};
class CfgGesturesMale
{
	class Default;
	class States
	{
		class CRPTHSBase: Default
		{
			canPullTrigger=0;
			connectAs="";
			connectFrom[]={};
			connectTo[]={};
			disableWeapons=0;
			enableBinocular=1;
			enableMissile=1;
			enableOptics=0;
			equivalentTo="";
			file="\A3\anims_f\Data\Anim\Sdr\gst\GestureHi.rtm";
			forceAim=0;
			headBobMode=0;
			headBobStrength=0;
			interpolateFrom[]={};
			interpolateTo[]={};
			interpolateWith[]={};
			interpolationRestart=0;
			interpolationSpeed=6;
			looped=0;
			mask="CRPTHSLeftArm";
			minPlayTime=0.5;
			preload=0;
			ragdoll=0;
			relSpeedMax=1;
			relSpeedMin=1;
			showHandGun=0;
			showItemInHand=0;
			showItemInRightHand=0;
			showWeaponAim=1;
			soundEdge[]={0.5,1};
			soundEnabled=1;
			soundOverride="";
			speed=-2;
			static=0;
			terminal=0;
			Walkcycles=1;
			weaponIK=1;
			leftHandIKBeg=1;
			leftHandIKCurve[]={0,1,0.1,0,0.80000001,0,1,1};
			leftHandIKEnd=1;
			rightHandIKBeg=1;
			rightHandIKCurve[]={1};
			rightHandIKEnd=1;
		};
		class CRPTHSForward: CRPTHSBase
		{
			file="\LG_animations\hand_signals\anims\crp_ths_forward.rtm";
			speed=1;
		};
		class CRPTHSForwardStandLowered: CRPTHSForward
		{
			file="\LG_animations\hand_signals\anims\crp_ths_forward_stand_lowered.rtm";
		};
		class CRPTHSStop: CRPTHSForward
		{
			file="\LG_animations\hand_signals\anims\crp_ths_stop.rtm";
			speed=0.60000002;
		};
		class CRPTHSStopStandLowered: CRPTHSStop
		{
			file="\LG_animations\hand_signals\anims\crp_ths_stop_stand_lowered.rtm";
		};
		class CRPTHSCover: CRPTHSForward
		{
			file="\LG_animations\hand_signals\anims\crp_ths_cover.rtm";
			speed=0.80000001;
		};
		class CRPTHSCoverStandLowered: CRPTHSCover
		{
			file="\LG_animations\hand_signals\anims\crp_ths_cover_stand_lowered.rtm";
		};
		class CRPTHSRegroup: CRPTHSForward
		{
			file="\LG_animations\hand_signals\anims\crp_ths_regroup.rtm";
			speed=0.80000001;
		};
		class CRPTHSRegroupStandLowered: CRPTHSRegroup
		{
			file="\LG_animations\hand_signals\anims\crp_ths_regroup_stand_lowered.rtm";
		};
		class CRPTHSEngage: CRPTHSForward
		{
			file="\LG_animations\hand_signals\anims\crp_ths_engage.rtm";
			speed=0.89999998;
		};
		class CRPTHSEngageStandLowered: CRPTHSEngage
		{
			file="\LG_animations\hand_signals\anims\crp_ths_engage_stand_lowered.rtm";
		};
		class CRPTHSPoint: CRPTHSForward
		{
			file="\LG_animations\hand_signals\anims\crp_ths_point.rtm";
			speed=0.80000001;
		};
		class CRPTHSPointStandLowered: CRPTHSPoint
		{
			file="\LG_animations\hand_signals\anims\crp_ths_point_stand_lowered.rtm";
		};
		class CRPTHSHold: CRPTHSForward
		{
			file="\LG_animations\hand_signals\anims\crp_ths_hold.rtm";
			speed=0.80000001;
		};
		class CRPTHSHoldStandLowered: CRPTHSHold
		{
			file="\LG_animations\hand_signals\anims\crp_ths_hold_stand_lowered.rtm";
		};
		class CRPTHSWarning: CRPTHSForward
		{
			file="\LG_animations\hand_signals\anims\crp_ths_warning.rtm";
			speed=0.80000001;
		};
		class CRPTHSWarningStandLowered: CRPTHSWarning
		{
			file="\LG_animations\hand_signals\anims\crp_ths_warning_stand_lowered.rtm";
		};
		class BP_Drink_Erc_x3_Gesture: Default
		{
			file="\LG_animations\BP\anims\BP_Drink_Erc_x3_Gesture.rtm";
			looped=0;
			speed=0.1;
			duty=0;
			aimingBody="aimingUpDefault";
			mask="LeftHandFeed";
			leftHandIKBeg=0;
			leftHandIKCurve[]={};
			leftHandIKEnd=1;
			rightHandIKBeg=1;
			rightHandIKCurve[]={};
			rightHandIKEnd=1;
			weaponIK=1;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=0;
			disableWeaponsLong=0;
			canPullTrigger=1;
			InterpolateTo[]={};
			interpolateFrom[]={};
			soundOverride="";
		};
		class BP_Eat_Erc_x3_Gesture: Default
		{
			file="\LG_animations\BP\anims\BP_Eat_Erc_x3_Gesture.rtm";
			looped=0;
			speed=0.1;
			duty=0;
			aimingBody="aimingUpDefault";
			mask="LeftHandFeed";
			leftHandIKBeg=0;
			leftHandIKCurve[]={};
			leftHandIKEnd=1;
			rightHandIKBeg=1;
			rightHandIKCurve[]={};
			rightHandIKEnd=1;
			weaponIK=1;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=0;
			disableWeaponsLong=0;
			canPullTrigger=1;
			InterpolateTo[]={};
			interpolateFrom[]={};
			soundOverride="";
		};
		class LG_anim_placec4: Default
		{
			file="\LG_animations\bank\anim\placec4.rtm";
			looped=0;
			speed=-1;
			mask="placeC4";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0};
		};
		class LG_suck_it: Default
		{
			file="\LG_animations\menu_gestures\anims\suck_it.rtm";
			looped=0;
			speed=-8.5;
			mask="suckIT";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0};
		};
		class LG_thumbs_down: Default
		{
			file="\LG_animations\menu_gestures\anims\LG_thumbs_down.rtm";
			looped=0;
			speed=-4;
			mask="suckIT";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0};
		};
		class LG_thumbs_up: Default
		{
			file="\LG_animations\menu_gestures\anims\LG_thumbs_up.rtm";
			looped=0;
			speed=-4;
			mask="suckIT";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0};
		};
		class LG_wanker: Default
		{
			file="\LG_animations\menu_gestures\anims\wanker.rtm";
			looped=0;
			speed=-4;
			mask="suckIT";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0};
		};
		class LG_no_way: Default
		{
			file="\LG_animations\menu_gestures\anims\no_way.rtm";
			looped=0;
			speed=-2.5999999;
			mask="suckIT";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0};
		};
		class LG_yes: Default
		{
			file="\LG_animations\menu_gestures\anims\yes.rtm";
			looped=0;
			speed=-2.5999999;
			mask="suckIT";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0};
		};
		class LG_that_way: Default
		{
			file="\LG_animations\menu_gestures\anims\that_way.rtm";
			looped=0;
			speed=-4.1999998;
			mask="suckIT";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0};
		};
		class LG_hitchhiking: Default
		{
			file="\LG_animations\menu_gestures\anims\hitchhiking.rtm";
			looped=0;
			speed=-4.5;
			mask="suckIT";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0};
		};
		class LG_anim_Hammer: Default
		{
			file="\LG_animations\tools\anims\hammergather.rtm";
			looped=0;
			speed=-6;
			mask="handsWeapon";
		};
	};
	class BlendAnims
	{
		class MaskStart
		{
			weight=0.85000002;
		};
		empty[]={};
		placeC4[]=
		{
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"Pelvis",
			1,
			"LeftLeg",
			1,
			"LeftLegRoll",
			1,
			"LeftUpLeg",
			1,
			"LeftUpLegRoll",
			1,
			"LeftFoot",
			1,
			"LeftToeBase",
			1,
			"RightLeg",
			1,
			"RightLegRoll",
			1,
			"RightUpLeg",
			1,
			"RightUpLegRoll",
			1,
			"RightFoot",
			1,
			"RightToeBase",
			1
		};
		suckIT[]=
		{
			"head",
			0.89999998,
			"neck1",
			0.80000001,
			"neck",
			0.69999999,
			"RightShoulder",
			1,
			"RightArm",
			1,
			"RightArmRoll",
			1,
			"RightForeArm",
			1,
			"RightForeArmRoll",
			1,
			"RightHand",
			1,
			"RightHandRing",
			1,
			"RightHandPinky1",
			1,
			"RightHandPinky2",
			1,
			"RightHandPinky3",
			1,
			"RightHandRing1",
			1,
			"RightHandRing2",
			1,
			"RightHandRing3",
			1,
			"RightHandMiddle1",
			1,
			"RightHandMiddle2",
			1,
			"RightHandMiddle3",
			1,
			"RightHandIndex1",
			1,
			"RightHandIndex2",
			1,
			"RightHandIndex3",
			1,
			"RightHandThumb1",
			1,
			"RightHandThumb2",
			1,
			"RightHandThumb3",
			1,
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"Spine",
			0.1,
			"Spine1",
			0.2,
			"Spine2",
			0.40000001,
			"Spine3",
			0.60000002
		};
		CRPTHSLeftArm[]=
		{
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1
		};
		aimingUpDefault[]=
		{
			"weapon",
			1,
			"Camera",
			1,
			"launcher",
			1,
			"Head",
			1,
			"Neck",
			1,
			"Neck1",
			1,
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"RightShoulder",
			1,
			"RightArm",
			1,
			"RightArmRoll",
			1,
			"RightForeArm",
			1,
			"RightForeArmRoll",
			1,
			"RightHand",
			1,
			"RightHandRing",
			1,
			"RightHandPinky1",
			1,
			"RightHandPinky2",
			1,
			"RightHandPinky3",
			1,
			"RightHandRing1",
			1,
			"RightHandRing2",
			1,
			"RightHandRing3",
			1,
			"RightHandMiddle1",
			1,
			"RightHandMiddle2",
			1,
			"RightHandMiddle3",
			1,
			"RightHandIndex1",
			1,
			"RightHandIndex2",
			1,
			"RightHandIndex3",
			1,
			"RightHandThumb1",
			1,
			"RightHandThumb2",
			1,
			"RightHandThumb3",
			1,
			"spine3",
			0.94999999,
			"spine2",
			0.89999998,
			"spine1",
			0.80000001,
			"spine",
			0.69999999
		};
		LeftHandFeed[]=
		{
			"head",
			1,
			"neck1",
			1,
			"neck",
			1,
			"weapon",
			0,
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"RightShoulder",
			0,
			"RightArm",
			0,
			"RightArmRoll",
			0,
			"RightForeArm",
			0,
			"RightForeArmRoll",
			0,
			"RightHand",
			0,
			"RightHandRing",
			0,
			"RightHandPinky1",
			0,
			"RightHandPinky2",
			0,
			"RightHandPinky3",
			0,
			"RightHandRing1",
			0,
			"RightHandRing2",
			0,
			"RightHandRing3",
			0,
			"RightHandMiddle1",
			0,
			"RightHandMiddle2",
			0,
			"RightHandMiddle3",
			0,
			"RightHandIndex1",
			0,
			"RightHandIndex2",
			0,
			"RightHandIndex3",
			0,
			"RightHandThumb1",
			0,
			"RightHandThumb2",
			0,
			"RightHandThumb3",
			0,
			"Spine",
			0,
			"Spine1",
			0,
			"Spine2",
			0,
			"Spine3",
			0,
			"pelvis",
			"MaskStart"
		};
	};
};
